apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wazuh-agent
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      volumes:
      - name: log-dir
        hostPath:
          path: /var/log/

      containers:
      - image: nidp/wazuh-agent
        name: wazuh-agent
        volumeMounts: 
        - name: log-dir
          mountPath: /var/log/
        env:
        - name: JOIN_MANAGER
          value: "IP ADDR"
        - name: JOIN_MANAGER_MASTER_HOST
          value: "IP ADDR"
        - name: JOIN_MANAGER_WORKER_HOST
          value: "IP ADDR"
        - name: JOIN_MANAGER_PROTOCOL
          value: "https"
        - name: NODE_NAME
          value: "TEST"
        - name: WAZUH_GROUPS
          value: NID
        - name: JOIN_MANAGER_API_PORT
          value: "55000"
        - name: JOIN_MANAGER_PORT
          value: "1514"
        - name: HEALTH_CHECK_PROCESSES
          value: "ossec-execd,ossec-syscheckd,ossec-logcollector,wazuh-modulesd,ossec-authd"
